version: "3.7"
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
  fastapi_app:
    image: menoitami/basketball-mm
    command: [ "/fastapi_app/docker/app.sh" ]
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - custom
    depends_on:
      - db
    environment:
      MONGO_USERNAME: rootuser
      MONGO_PASSWORD: rootpass
      MONGO_HOSTNAME: db
      MONGO_PORT: 27017
      MONGO_DB: your_db_name
networks:
  custom:
    driver: bridge
volumes:
  db-data: