services:
  db:
    image: mongo
    restart: always
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - custom
  fastapi_app:
    build:
      context: .
    container_name: fastapi_app
    command: [ "/fastapi_app/docker/app.sh" ]
    ports:
      - "8000:8000"
    networks:
      - custom
    depends_on:
      - db
    environment:
      MONGO_HOSTNAME: db
      MONGO_PORT: 27017
      MONGO_DB: events
web:
    container_name: "web"
    image: nginx:alpine
    depends_on:
      - fastapi_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/conf.d:/etc/nginx/conf.d
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  db-data:
